using System.Collections.Generic;

namespace FIMSpace.FSpine
{
    public partial class FSpineAnimator
    {

        /// <summary>
        /// Destroying objects generated by component
        /// </summary>
        public void OnDestroy()
        {
            RemovePivotOffset();
        }


        /// <summary>
        /// Supporting generating additional pivot transform
        /// </summary>
        void OnValidate()
        {
            if (SpineBones == null) SpineBones = new List<SpineBone>();
            UpdatePivotOffsetState();
            if (UseCollisions) CheckForColliderDuplicates();
            if (UpdateRate < 0f) UpdateRate = 0f;

            ModelRightAxis = UnityEngine.Vector3.Cross(ModelForwardAxis, ModelUpAxis);
        }


        /// <summary>
        /// Adding connector component for spine animator for it to try sync bones after spine motion
        /// </summary>
        public void AddConnector(FSpineBoneConnector connector)
        {
            if (connectors == null) connectors = new List<FSpineBoneConnector>();
            if (!connectors.Contains(connector)) connectors.Add(connector);
        }

    }
}